### ISSUE TITLE
Creating new character and not saving info breaks app

### ISSUE THREAD

**Issue by arthyn** [zombieFox/awesomeSheet#106]
Looks like the app increments character index too early before any actual info is saved/character generated. This can be replicated by creating a new character without saving any information and then closing the tab. It then has an index of one greater than it should without a character to load which results in a JS error.

**Comment by zombieFox** [comment]
Thanks for the issue post. I'm sorry, I can't replicate the described bug. It would be really helpful if you could provide more details so I can investigate. I would really appreciate what computer/device you are using, the OS, the browser and its version number. Also, detailed step by step instructions to reach the JS error. And what the error in the console reads if possible. 

Thanks for taking time to feedback, I appreciate it.

**Comment by zombieFox** [comment]
Unable to replicate bug, closing the issue.
