### ISSUE TITLE
Change the order.

### ISSUE THREAD

**Issue by zautos** [zombieFox/awesomeSheet#111]
it would be better if it was.
Basics
Attack
Defence
Skills

it could also be 
Basics
Defence
Attack
Skills

also, damage type for weapons.

One more thing. a buff button. So if you click it apply the bonuses you selected and if you press it again it removes the bonuses. This would be useful for rogues

**Comment by zombieFox** [comment]
Appreciate the feedback. I'll work on adding weapon types to the attack blocks.

Can you elaborate on why moving the Equipment section down would be useful? I'm happy to give it some thought.

**Comment by zautos** [comment]
when playing the Character. The equipment section is less important than
attack, deffence, and skills.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfritt.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by zombieFox** [comment]
Weapon types have been added in a recent update.

I'll investigate moving sections. This may also be resolved by other redesign work (redesign of the display mode which will kick off soon).

Thanks for all the feedback. Closing the issue.
