### ISSUE TITLE
Custom Skills

### ISSUE THREAD

**Issue by DigiBear** [zombieFox/awesomeSheet#123]
Custom skills don't seem to appear in the skill list whenever the sheet is in View Mode.

As can be seen [here](https://gyazo.com/e7e03dcf20641d3f20378f283a7643cf) the custom skills Track and Wild Empathy from the Ranger list have been added however [here](https://gyazo.com/e18b8a4bb77ec6c9aaaf1dc3340a4128) they cannot be seen in the full list.

**Comment by zombieFox** [comment]
Many thanks for alerting me to this bug. A fix has just been pushed out (snuck in alongside a new feature release). I'm testing it now and so far looks like the problem has been resolved.

**Comment by DigiBear** [comment]
Glad to help!!

On 12 Jan 2018 19:30, Kuldeep M <notifications@github.com> wrote:

Many thanks for alerting me to this bug. A fix has just been pushed out (snuck in alongside a new feature release). I'm testing it now and so far looks like the problem has been resolved.
