### ISSUE TITLE
Update Function

### ISSUE THREAD

**Issue by DigiBear** [zombieFox/awesomeSheet#129]
I've been working with the sheets now on both tablet and PC for 4 different characters now and one thing I might suggest is adding an update function next to Import and Export.

I often find myself saving the .Json file to my Google drive to then download it and import it on the other after having updated the character sheet (such as having added new items or notes), Every time I do this however I find myself having to delete the previous version since it Imports the .Json as a new character. 

Updating the current character sheet instead of constantly creating new ones would really smooth out the experience.

Thank you for the Awesome, awesomeSheets, they've been great sofar!

**Comment by zombieFox** [comment]
This should be possible. I will definitely look into this as a new feature. I've got a couple of fixes to complete first so expect this to be picked up later in the week.

**Comment by zombieFox** [comment]
Feature has been added and pushed to live.
