### ISSUE TITLE
[feature request] Description modals for feats and class features.

### ISSUE THREAD

**Issue by B1rch** [zombieFox/awesomeSheet#134]
Hey there, been using your sheet for quite a while now. Loving it so far, but I find it cumbersome to memorize exactly what my feats and class features do. Especially for the more convoluted ones.

Would it be possible to add the kind of interaction spells have currently to feats and class features? I would love to be able to add a description and have a modal pop-up when in display mode.

I would be willing to help out with the implementation if necessary, I have experience with web development.

**Comment by zombieFox** [comment]
Hi, glad to hear. That is very possible. I'm already planning that feature. 

I'm investigating how the Feats section can reuse the Spell section "search and add" feature. However that will likely take a long time to develop (1 or 2 months). So the first iteration I'm planning is a simple feat add flow:

1. enter feat name in an input field on page
2. click add/hit enter
3. feat button appears with name on page
4. feat button clicked
5. modal with feat name appears with inputs to:
   * rename feat
   * add notes/feat details

This first iteration should kick off in a week, maybe two. I'm currently busy with a [large refactor job](https://github.com/zombieFox/awesomeSheet/tree/orginiseData).

Help would always be welcome!

**Comment by B1rch** [comment]
Awesome! Shoot me an email sometime, glad to help out

**Comment by zombieFox** [comment]
A beta build of the new Pill features is now live. See [betaSheet](https://zombiefox.github.io/betaSheet/). Feedback is welcome.

### **Caution** 
Only view betaSheet a private window (eg incognito mode on Chrome) as it will break any awesomeSheet data stored on currently your browser.

**Comment by zombieFox** [comment]
Feature is now live. Closing issue.
