### ISSUE TITLE
[Feedback] Auto Calculate Item Quantities

### ISSUE THREAD

**Issue by DigiBear** [zombieFox/awesomeSheet#138]
It would be cool if the total wealth and weight would automatically be adjusted by the quantity of items I would carry.  I don't know if it's common that people prefer to do that type of bookkeeping by hand but if so it should be fairly easy to just have a checkbox ticking "auto-calculate" on and off.

*e.g. if I carry 2 Scroll boxes I would just keep the cost and weight at 5gp and 1lbs. and just change the quantity to automatically adjust the total value and weight of those items*

In case you use arrays it should be fairly easy to have entry 2 and 3 be multiplied by entry 1 before being added to the total I think *(My Knowledge(javascript) is pretty rusty though so sorry if I assumed)*

As an aside, it would be awesome if the quantity of an item could be linked to consumables by them having the same name for example, but I think that might be one big database mess so absolutely no pressure in putting that in!

**Comment by zombieFox** [comment]
A very good idea, this should be possible. Not sure of the solution right now but an investigation of this problem should be easy.

Thanks for all the suggestions, I've started to add feature suggestions to a Projects page called [Feature Development](https://github.com/zombieFox/awesomeSheet/projects/1). I'll try to make sure it shows current progress of task like this, so you can see what I'm currently working on.

**Comment by zombieFox** [comment]
#144

**Comment by zombieFox** [comment]
Feature is now live. Closing issue.
