### ISSUE TITLE
Senses

### ISSUE THREAD

**Issue by gregschein** [zombieFox/awesomeSheet#146]
Just suggesting putting senses somewhere on the sheet. Low light, darkvision, blindsight/sense, etc.

**Comment by zombieFox** [comment]
A good thought, I can add this. 

Initial thoughts are to add it to the Basics section. Any thoughts for where else this addition might live?

**Comment by gregschein** [comment]
Basics is what I thought as well. Only other place it would maybe fit is abilities?

**Comment by zombieFox** [comment]
Sounds right, Basics it is. I've added it to my project board: https://github.com/zombieFox/awesomeSheet/projects

**Comment by zombieFox** [comment]
Feature is now live
