### ISSUE TITLE
Broken Level modifier

### ISSUE THREAD

**Issue by DigiBear** [zombieFox/awesomeSheet#148]
It seems that the level modifier on stats can't find the right array anymore. Currently, it gives **Level([object Object])** and selecting it gives no bonus whatsoever.

![](https://i.gyazo.com/628f875b874fa55af852a668b987998f.png)

There's probably an obsolete link somewhere that causes this bug.

Great work on the AwesomeSheet by the way.. they're awesome and they make playing pathfinder fun again!

**Comment by zombieFox** [comment]
Good find, I also just noticed it. I'm releasing a fix right now (should be like now) 👍 

Thanks very much for the feedback, glad awesomeSheet is helpful to you.
