### ISSUE TITLE
[Question] Would you be interested in adding dungeon master tools?

### ISSUE THREAD

**Issue by JacobDB** [zombieFox/awesomeSheet#153]
I just stumbled across this, and couldn't believe how awesome it looks. I'm new to Pathfinder myself, but my DM has been looking for a tool kind of like this for a while now, and he just recently settled on [roll20](https://roll20.net/). While it's very full featured, it's a pretty terrible system (very slow, doesn't work on phones, ugly design).

I'd love to convince him to switch to this, but a big part of why he's using roll20 is their DM-ing tools. I know this is likely out of the scope of this particular project, but what would you think about building some form of companion app for the DM side of the game?

We haven't really started using roll20 yet, but from my limited experience, and poking around their website, I think this should cover a good portion of the features provided:

- Private and group messaging
- Sharing documents (including transcriptions)
- Displaying maps, moving characters and NPCs around them, and showing/hiding sections based on a lighting model
- Viewing/editing player character sheets (and keeping them in sync real-time)

I'm probably missing a lot of major features, I'll come back after I speak with him with more information.

I'm a professional web developer myself, and I'd be happy to work with you to build this. Granted, I mostly work on WordPress sites, but I'm semi-capable with JavaScript & Node, and I'm definitely open to learning more in order to get this thing up and running.

I may be getting ahead of myself, but I have some ideas floating around as to how this companion app could work in conjunction with awesomeSheet, and I'm just going to throw down some notes here:

- Build with Node JS, allow serving either locally or via custom hosting
- Authenticate with OAuth, prevents issues with storing usernames/password securely
- Use [Socket.io](https://socket.io) for a chat system and keeping character sheets in sync
- Tweak save function to save to a database if configured to do so (for example, if a file database.json exists, save to the configured database as well as locally (keeping data in sync may be tricky), otherwise, continue to function exactly as it does)

Let me know what you think! I'll report back later this week with more information from my DM!

**Comment by JacobDB** [comment]
After talking with my DM last week, I think that recreating roll20 would be quite ambitious, and not something an individual or small team could likely take on on their own. Closing for now, but maybe at some point in the future it'll be worth reconsidering.

**Comment by zombieFox** [comment]
Hi, I'm happy you like using awesomeSheet, the project has been in development for a long time and I'm glad to see it being received well.

The ideas you have listed are very exciting and ambitious. I can see these and tools features would bring a lot of value to DM's and players alike. That being said my ability to realistically build and deliver them might not be as straight forward. I have limited time to commit to work like this and tend to only spend some free time outside of work developing awesomeSheet. Another tool/project would not be something I could commit to right now, especially as some of the ideas above very large in scope. I am familiar with roll20 and know that many of the skills needed to build something similar would be outside of my understanding and skill set. 

That is not to say I wouldn't be very happy to contribute to a project of this type should you decide to begin work on it. I will happily commit to helping a new project with user experience and interface input, as these are my primary skills. 

Some of the points you've listed have been said by others however, specifically the possible scope of viewing and editing character sheets within a group. This could be a small and more realistic step towards bringing value to users. Would having private and sharable sheets be something you might be interested in helping develop? A rough outline of scope would be:

- user accounts with oAuth services (log in with fb / google etc. accounts)
- view / editing sheets once logged in
- associate a sheet with group (read, edit)
- availability to save sheets to DB (maybe with versioning)
- within a group, DM can edit other players sheets (maybe with versioning)
- shared with groups or individuals

A lot of the above is, again, outside of my knowledge so would be a learning exercise but something I would be happy to commit it for long term development/additions.
