### ISSUE TITLE
Untrained Skill Visibility

### ISSUE THREAD

**Issue by Suunami** [zombieFox/awesomeSheet#154]
Requesting skill list to show skills with 0 ranks that do not require training. Current version only shows skills with 1 or more ranks in Display Mode.

**Comment by zombieFox** [comment]
Do you mean when a Skill can be attempted without being trained? I think that's a reasonable change. The current log is to show any skill which has Ranks in it. I'll investigate how to go about supporting untrained Skills too.

**Comment by zombieFox** [comment]
I've added a task to the project board: https://github.com/zombieFox/awesomeSheet/projects/1
Let me know if needs to be changed (I need to read up on trained and untrained skills).

**Comment by Suunami** [comment]
You nailed it, apologies if my wording was confusing. Thanks a lot, you're the best!

**Comment by zombieFox** [comment]
#155

**Comment by zombieFox** [comment]
Feature is now live

**Comment by Suunami** [comment]
You are a beast
