### ISSUE TITLE
Bug: Armor Check Penalty is added to the Skill Bonus instead of substracted.

### ISSUE THREAD

**Issue by mibib7** [zombieFox/awesomeSheet#161]
![image](https://user-images.githubusercontent.com/25063286/38707853-3f7ea6b0-3e81-11e8-9803-7411149897b5.png)

![image](https://user-images.githubusercontent.com/25063286/38707861-477f7b78-3e81-11e8-9af9-e87d7e264590.png)

As you can see, the total is calculated as Ranks (3) + Dex (3) + ACP (2) = 8.
The real total should be Ranks (3) + Dex (3) - ACP (2) = 4.

I understand that I can just insert the ACP as an negative value for the calculation to be accurate, but considering that ACP can never be negative (as in giving a bonus instead of a malus) and that in the game material ACP is given as a positive value, it is confusing having to put a negative value.

**Comment by zombieFox** [comment]
Hi, actually I believe the Armor Check Penalty is always a negative number. It can never be a positive number. It is listed as negative numbers in the [armor and shields section on the PRD](http://paizo.com/pathfinderRPG/prd/coreRulebook/equipment.html#table-6-6-armor-and-shields).

As such the input for Armor Check Penalty is applied (or added) to the Skills which accept it.

**Comment by mibib7** [comment]
You are right, my bad. 
Keep up the good work.
