### ISSUE TITLE
Level Modifier disconnected

### ISSUE THREAD

**Issue by DigiBear** [zombieFox/awesomeSheet#164]
it seems the level modifier on skills, spells concentration etc has been disconnected again with the latest patch. the character in the example is level 5.

![image](https://user-images.githubusercontent.com/26846158/39085050-dba2f03e-457d-11e8-861c-1b5553b8bfe9.png)

Cheers!

**Comment by zombieFox** [comment]
Hi. I believe the Level Bonus is working as intended. The Level Bonus is derived from the Experience and the chosen Experience Progression Track, this was introduced a few iterations ago.

If no Progression Track in Basics > EXP is not selected the webapp can't determine certain details in the background. What I could do is find a way to explain this better in the Basics section.

**Comment by DigiBear** [comment]
You are entirely correct!
Guess I wasn't paying attention, sorry for the inconvenience!

**Comment by zombieFox** [comment]
I do think there is a disconnect with the Class tab and the Experience tab. Maybe some visual connection is needed to make clear how the calculated EXP shows as Levels which can be "spent" in the Class Tab.

**Comment by DigiBear** [comment]
hmmm.. what you could do is transcribe some code that you have from the Skills section. 

Just at the bottom of the classes section place a little box, same as the skills fro amount of points left, that shows the amount of levels you still have left to spend. 
It would just take the input of the exp tab and output it at the Class tab without affecting anything in a big way so that we don't get in a cinch when we want to multiclass or anything.

I can make a visual representation of it if you want

**Comment by DigiBear** [comment]
You are too good for me man.. I've been blind to all that you updated already in my haste. I think this way it'll generally work itself out, I mostly just did a stupid earlier since I was just quickly throwing a character together for a friend of mine. 

In case you really want to put an emphasis on it however you could make sure that the Levels section is considered read-only until a progression speed has been chosen. it would force people to think for a second before they act (like I did...) and learn to understand the system.
