### ISSUE TITLE
Print Mode Font Colour

### ISSUE THREAD

**Issue by DigiBear** [zombieFox/awesomeSheet#166]
Hey, just a quick little bug I found.

When trying to print the page out the base font colour is retained. this means that when printing while in dark mode you'll have light gray text on a white background. Nothing bad or anything but thought I'd let you know!

**Comment by zombieFox** [comment]
That is an interesting scenario, I wouldn't call a problem as there is a way to work around this issue by switching to Display Mode before printing. That being said I want to explore the idea of detecting the print event and invoking a function. I've investigated and refactored the Minimise, Display mode and Night Mode modules. 

New functionality which will be released in short while (I'm testing it now):

**On print:** 
- Force Display Mode on
- Force Night Mode off
- Force Minimise mode off

**After print:**
- Restore previous Display Mode state
- Restore previous Night Mode state
- Restore previous Minimise Mode state

**Comment by zombieFox** [comment]
Feature is now live.
