### ISSUE TITLE
Update Build, Replace Bower

### ISSUE THREAD

**Issue by johnantoni** [zombieFox/awesomeSheet#169]
Hi, I'm going to try and port the app to Yarn & Webpack

Is that ok? Any issues with using Yarn?

Just know that Bower is unmaintained and can probably get it running under webpack which could make future development easier.

**Comment by zombieFox** [comment]
Hi, I've not got much experience with Yarn and only know a bit about Webpack. But don't really mind what tooling to use. Would this be replacing Bower? Or Bower and Grunt?

**Comment by johnantoni** [comment]
it'd replace bower. grunt not sure about. probably keep that for the time being. Yarn is basically NPM with a few bells and whistles.

I'll start it and see how it goes, could be good.

**Comment by johnantoni** [comment]
no problem, glad you like it. gone thru the pull request and answered all your questions. please feel free to ask anything else.

Yep that game was a nail-biter so glad we're thru. First time since 1960, definitely check it out if you can they played great.
